name: MLflow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-train:
    runs-on: ubuntu-latest
    
    # Set MLFLOW_TRACKING_URI secara global untuk semua langkah
    # agar MLflow tahu di mana mencari folder 'mlruns'.
    env:
      MLFLOW_TRACKING_URI: ./MLProject/mlruns

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo "Tracking URI: ${{ env.MLFLOW_TRACKING_URI }}"
          echo $CSV_URL
          
      - name: Install dependencies
        run: |
          pip install mlflow pandas scikit-learn numpy

      - name: Run MLflow Project (Training & Logging)
        # Menjalankan dari direktori MLProject/ akan membuat data di ./MLProject/mlruns
        run: |
          cd MLProject
          mlflow run . --env-manager=local | tee modelling.log
          # Pindahkan log ke root agar bisa diakses di langkah selanjutnya
          mv modelling.log ..

      # Ambil run_id dari log yang sudah dipindahkan ke root
      - name: Ambil run_id dari log
        run: |
          RUN_ID=$(grep -oP 'RUN_ID=\K[0-9a-f]+' modelling.log)
          if [ -z "$RUN_ID" ]; then
            echo "❌ Gagal mendapatkan RUN_ID dari log."
            exit 1
          fi
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Run ID berhasil diambil: $RUN_ID"

      # Build Docker Model
      - name: Build Docker Model
        # MLFLOW_TRACKING_URI sudah disetel di bagian 'env' global
        run: |
          if [ -z "${{ env.RUN_ID }}" ]; then
            echo "❌ RUN_ID kosong, tidak bisa build Docker model"
            exit 1
          fi
          # Perintah ini sekarang akan mencari run ID di './MLProject/mlruns'
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name "submission"

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag submission ${{ secrets.DOCKER_HUB_USERNAME }}/submission:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/submission:latest
